FROM golang:1.24-alpine AS builder

ENV GOOS=linux \
    GOARCH=amd64

WORKDIR /app

RUN mkdir users-service

COPY users-service/go.mod ./users-service
COPY users-service/go.sum ./users-service
COPY shared ./shared

WORKDIR /app/users-service

RUN go mod download

COPY users-service/ ./

RUN go build -o server main.go

FROM alpine:latest

WORKDIR /root/
COPY --from=builder /app/users-service/server ./

EXPOSE 8080
CMD ["./server"]
